sudo: required
services:
  - docker

before_install:
  - docker build -t fsved/standard_complex -f ./client/Dockerfile.dev ./client

script:
  - docker run fsved/standard_complex npm test -- --coverage

after_success:
  - docker build -t fsved/std-complex_client ./client
  - docker build -t fsved/std-complex_nginx ./nginx
  - docker build -t fsved/std-complex_server ./server
  - docker build -t fsved/std-complex_worker ./worker

  # Login ot the docker CLI in one single command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push separate container images to Docker hub
  - docker push fsved/std-complex_client
  - docker push fsved/std-complex_nginx
  - docker push fsved/std-complex_server
  - docker push fsved/std-complex_worker

  - docker logout

deploy:
  # edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: standard-complex
  env: StandardComplex-env
  bucket_name: elasticbeanstalk-us-east-2-163264011359
  bucket_path: standard-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY